# Configuration for WPDistillery executed by setup.sh
#
# Author: Flurin DÃ¼rst
# URL: https://wpdistillery.org
#
# For detailed instructions on this file read the config.yml-documentation at
# https://wpdistillery.org/documentation/config-yml-documentation/
#
# File Version: 1.8.3


# INSTALLATION
#################################################################

# WordPress version
wpversion: latest

# language/timezone
wplocale: en_US
timezone: "America/New_York"

# admin user settings
admin:
  user: admin
  password: admin
  email: mail@domain.tld
  first_name: ""
  last_name: ""

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# SETTINGS
#################################################################

wpsettings:
  url: wpdistillery.vm
  title: Example Title
  description: Example Description
  permalink_structure: "/%postname%/"
  thumbnail_width: 150
  thumbnail_height: 150
  medium_width: 300
  medium_height: 300
  large_width: 1024
  large_height: 1024
  # use page as frontpage
  page_on_front: true
  # define frontpage name (requires `page_on_front: true`)
  frontpage_name: Example Front Page
  # automatic conversion of smilies
  convert_smilies: false

# THEMES
#################################################################

# install a custom theme via url, rename it and remove the default themes
theme:
  name: WPSeed
  url: "https://github.com/flurinduerst/WPSeed/archive/master.zip"
  rename: ""
  remove:
    - twentyfifteen
    - twentysixteen
    - twentyseventeen


# PLUGINS
#################################################################

# plugins to install & activate
plugins_active:
  - disable-comments
  - duplicate-post
  - enable-media-replace
  - favicon-by-realfavicongenerator
  - regenerate-thumbnails
  - simple-page-ordering
  - user-switching

# plugins to install
plugins_inactive:
  #development
  - search-and-replace
  # seo
  - autodescription
  #security/backup
  - backwpup

# WPDISTILLERY SETUP
####################################################################
# if you don't want the setup to run all tasks, set them to false

setup:
  wp: true
  settings: true
  theme: true
  plugins: true
  cleanup: true
  # adjust what data you want to be deleted within the cleanup (requires `cleanup: true`)
  comment: true
  posts: true
  files: true
